---
title: "Instacart Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(viridis)
library(p8105.datasets)
library(plotly)

instacart = instacart %>% 
  janitor::clean_names()
```

Column {data-width=500}
-----------------------------------------------------------------------

### Number of order in each department

```{r}
instacart %>% 
  count(department) %>% 
  mutate(department = fct_reorder(department,n)) %>% 
  plot_ly(x = ~department, y = ~n ,color = ~department, type = "bar")
```

Column {data-width=500}
-----------------------------------------------------------------------

### Number of order changes during a day

```{r}
instacart %>% 
  count(order_hour_of_day) %>% 
  plot_ly(x = ~order_hour_of_day, y = ~n, type = "scatter", mode = "line")
```

### Number of orders of produce in a day

```{r}
instacart %>% 
  filter(department == "produce") %>% 
  plot_ly(y = ~order_hour_of_day, color = ~aisle, type = "box",
          colors = "Set2")
```
